version: "3.9"
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      VETAPP_DB_PASS: 6378
      VETAPP_DB_URL: jdbc:postgresql://postgres:5432/
      VETAPP_DB_NAME: VeterinaryManagementSystem
      VETAPP_DB_USER: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6378
      POSTGRES_DB: VeterinaryManagementSystem
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: